services:
  auto_upgrader:
    image: ghcr.io/eclipsevortex/subvortex-auto-upgrader:latest
    container_name: subvortex-auto-upgrader
    restart: unless-stopped
    env_file:
      - ./subvortex/auto_upgrader/.env
    volumes:
      - /var/log:/app/logs
