services:
  auto_upgrader:
    build:
      context: ../../
      dockerfile: ./subvortex/auto_upgrader/Dockerfile
      additional_contexts:
        wheelbuilder: docker-image://ghcr.io/eclipsevortex/subvortex-wheel-builder:latest
    container_name: subvortex-auto-upgrader
    restart: unless-stopped
    env_file:
      - ./subvortex/auto_upgrader/.env
    volumes:
      - /var/log:/app/logs
